---

## Installation des composants
  - name: Installation des paquets nécessaire, testé sur xUbuntu 20.04 / 22.04
    become: yes
    apt:
      update_cache: yes
      name: "{{ packages }}"
    vars:
      packages:
      - zsh 
      - zsh-theme-powerlevel9k
      - zsh-syntax-highlighting
    tags: apt

  - name: creation du repertoire .zsh
    become: no
    file:
      path: "~/.zsh"
      state: directory
      mode: 0755
    tags: dir

  - name: Clone du module autosuggestions
    become: no
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: ~/.zsh
      force: yes
      version: master
    tags: git

  - name: Installation de oh-my-zsh
    become: no
    shell:
      cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    tags: ohmyzsh


## Personnalisation de .zshrc
  - name: Remplacement d'information dans le fichier ~/.zshrc
    become: no
    lineinfile:
      path: ~/.zshrc
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
    - { regexp: 'ZSH_THEME="robbyrussell"', line: 'ZSH_THEME="agnoster"' }
    - { regexp: 'plugins=\(git\)', line: 'plugins=(git colored-man-pages ansible cp sudo yum)' }
    - { regexp: '# HIST_STAMPS="mm/dd/yyyy"', line: 'HIST_STAMPS="yyyy-mm-dd"' }
    tags: personnalisation

  - name: Ajout d'information dans le fichier ~/.zshrc
    become: no
    lineinfile:
      path: ~/.zshrc
      insertafter: 'HIST_STAMPS="yyyy-mm-dd'
      line: "{{ item }}"
    with_items:
      - "export EDITOR='vim'"
      - 'export SSH_KEY_PATH="~/.ssh/rsa_id"'
      - '# Ajout clé ssh'
      - 'export HISTORY_IGNORE="(history|ls -ltr|ll|ls -la|lll|ls|pwd|exit|cd|cd ..)"'
      - "# Supprimer commande qui pollue l'historique"
      - 'setopt HIST_FIND_NO_DUPS'
      - '# Supprimer doublon de la recherche (ctrl+r)'
      - 'export HISTFILESIZE=200000'
      - 'export HISTSIZE=100000'
      - '# Limite et taille'
    tags: personnalisation

  - name: Ajout d'information dans le fichier ~/.bashrc
    become: no
    lineinfile:
      path: ~/.bashrc
      insertafter: 'HIST_STAMPS="yyyy-mm-dd'
      line: "{{ item }}"
    with_items:
      - '#sources'
      - 'source ~/.oh-my-zsh/oh-my-zsh.sh'
      - 'source /usr/share/powerlevel9k/powerlevel9k.zsh-theme'
      - 'source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
      - 'source ~/.zsh/zsh-autosuggestions.zsh'
    tags: personnalisation


  - name: preparation du shell zsh pour l'utilisateur
    become: yes
    vars:
      the_user: "{{ ansible_user_id }}"
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh
    tags: shell
